-------------------------DESPARECIDOS PERSONAS--------------------
INSERT INTO `desaparecidos_personas` (`edadExtravio`, `estatura`, `peso`, `idPersona`,  `idCedula`, `idComplexion`, `idColorPiel`) VALUES ('50 años, 10 meses y 9 dias', '167', '60', 5, 1, 2016, 13, NULL, NULL, NULL, 1, 1, 3, 1, '2018-05-31 23:23:29', '2018-05-31 23:26:00', NULL);
INSERT INTO `desaparecidos_personas` (`id`, `apodo`, `edadAparente`, `edadExtravio`, `embarazo`, `tipoGestacion`, `numGestacion`, `rumoresBebe`, `pormenores`, `antecedentesJudiciales`, `organizacion`, `tipoPersona`, `otroDocIdentidad`, `numDocIdentidad`, `otroParentesco`, `correoElectronico`, `telefonos`, `tieneHijos`, `informante`, `notificaciones`, `estatura`, `peso`, `idPersona`, `idEdocivil`, `idOcupacion`, `idEscolaridad`, `idDialecto`, `idCargo`, `idParentesco`, `idDocumentoIdentidad`, `idCedula`, `idComplexion`, `idColorPiel`, `created_at`, `updated_at`, `deleted_at`) VALUES (6, 'DANI', '27', '24 a�os, 8 meses y 4 dias', 'NO', NULL, NULL, 'NO', NULL, NULL, NULL, 'DESAPARECIDA', NULL, '5445345646', NULL, NULL, NULL, 0, 0, 0, '181', '80', 4, 1, 2472, 12, NULL, NULL, NULL, 1, 2, NULL, NULL, '2018-05-31 23:33:55', '2018-05-31 23:33:55', NULL);
INSERT INTO `desaparecidos_personas` (`id`, `apodo`, `edadAparente`, `edadExtravio`, `embarazo`, `tipoGestacion`, `numGestacion`, `rumoresBebe`, `pormenores`, `antecedentesJudiciales`, `organizacion`, `tipoPersona`, `otroDocIdentidad`, `numDocIdentidad`, `otroParentesco`, `correoElectronico`, `telefonos`, `tieneHijos`, `informante`, `notificaciones`, `estatura`, `peso`, `idPersona`, `idEdocivil`, `idOcupacion`, `idEscolaridad`, `idDialecto`, `idCargo`, `idParentesco`, `idDocumentoIdentidad`, `idCedula`, `idComplexion`, `idColorPiel`, `created_at`, `updated_at`, `deleted_at`) VALUES (7, 'PEPE', '54', '50 a�os, 10 meses y 9 dias', 'NO', NULL, NULL, 'NO', NULL, NULL, NULL, 'DESAPARECIDA', NULL, '23232323', NULL, NULL, NULL, 0, 0, 0, '167', '60', 2, 1, 2016, 13, NULL, NULL, NULL, 1, 1, 3, 1, '2018-05-31 23:23:29', '2018-05-31 23:26:00', NULL);
INSERT INTO `desaparecidos_personas` (`id`, `apodo`, `edadAparente`, `edadExtravio`, `embarazo`, `tipoGestacion`, `numGestacion`, `rumoresBebe`, `pormenores`, `antecedentesJudiciales`, `organizacion`, `tipoPersona`, `otroDocIdentidad`, `numDocIdentidad`, `otroParentesco`, `correoElectronico`, `telefonos`, `tieneHijos`, `informante`, `notificaciones`, `estatura`, `peso`, `idPersona`, `idEdocivil`, `idOcupacion`, `idEscolaridad`, `idDialecto`, `idCargo`, `idParentesco`, `idDocumentoIdentidad`, `idCedula`, `idComplexion`, `idColorPiel`, `created_at`, `updated_at`, `deleted_at`) VALUES (8, 'DANI', '27', '24 a�os, 8 meses y 4 dias', 'NO', NULL, NULL, 'NO', NULL, NULL, NULL, 'DESAPARECIDA', NULL, '5445345646', NULL, NULL, NULL, 0, 0, 0, '181', '80', 4, 1, 2472, 12, NULL, NULL, NULL, 1, 2, NULL, NULL, '2018-05-31 23:33:55', '2018-05-31 23:33:55', NULL);
INSERT INTO `desaparecidos_personas` (`id`, `apodo`, `edadAparente`, `edadExtravio`, `embarazo`, `tipoGestacion`, `numGestacion`, `rumoresBebe`, `pormenores`, `antecedentesJudiciales`, `organizacion`, `tipoPersona`, `otroDocIdentidad`, `numDocIdentidad`, `otroParentesco`, `correoElectronico`, `telefonos`, `tieneHijos`, `informante`, `notificaciones`, `estatura`, `peso`, `idPersona`, `idEdocivil`, `idOcupacion`, `idEscolaridad`, `idDialecto`, `idCargo`, `idParentesco`, `idDocumentoIdentidad`, `idCedula`, `idComplexion`, `idColorPiel`, `created_at`, `updated_at`, `deleted_at`) VALUES (9, 'PEPE', '54', '50 a�os, 10 meses y 9 dias', 'NO', NULL, NULL, 'NO', NULL, NULL, NULL, 'DESAPARECIDA', NULL, '23232323', NULL, NULL, NULL, 0, 0, 0, '167', '60', 2, 1, 2016, 13, NULL, NULL, NULL, 1, 1, 3, 1, '2018-05-31 23:23:29', '2018-05-31 23:26:00', NULL);
INSERT INTO `desaparecidos_personas` (`id`, `apodo`, `edadAparente`, `edadExtravio`, `embarazo`, `tipoGestacion`, `numGestacion`, `rumoresBebe`, `pormenores`, `antecedentesJudiciales`, `organizacion`, `tipoPersona`, `otroDocIdentidad`, `numDocIdentidad`, `otroParentesco`, `correoElectronico`, `telefonos`, `tieneHijos`, `informante`, `notificaciones`, `estatura`, `peso`, `idPersona`, `idEdocivil`, `idOcupacion`, `idEscolaridad`, `idDialecto`, `idCargo`, `idParentesco`, `idDocumentoIdentidad`, `idCedula`, `idComplexion`, `idColorPiel`, `created_at`, `updated_at`, `deleted_at`) VALUES (10, 'DANI', '27', '24 a�os, 8 meses y 4 dias', 'NO', NULL, NULL, 'NO', NULL, NULL, NULL, 'DESAPARECIDA', NULL, '5445345646', NULL, NULL, NULL, 0, 0, 0, '181', '80', 4, 1, 2472, 12, NULL, NULL, NULL, 1, 2, NULL, NULL, '2018-05-31 23:33:55', '2018-05-31 23:33:55', NULL);
INSERT INTO `desaparecidos_personas` (`id`, `apodo`, `edadAparente`, `edadExtravio`, `embarazo`, `tipoGestacion`, `numGestacion`, `rumoresBebe`, `pormenores`, `antecedentesJudiciales`, `organizacion`, `tipoPersona`, `otroDocIdentidad`, `numDocIdentidad`, `otroParentesco`, `correoElectronico`, `telefonos`, `tieneHijos`, `informante`, `notificaciones`, `estatura`, `peso`, `idPersona`, `idEdocivil`, `idOcupacion`, `idEscolaridad`, `idDialecto`, `idCargo`, `idParentesco`, `idDocumentoIdentidad`, `idCedula`, `idComplexion`, `idColorPiel`, `created_at`, `updated_at`, `deleted_at`) VALUES (11, 'PEPE', '54', '50 a�os, 10 meses y 9 dias', 'NO', NULL, NULL, 'NO', NULL, NULL, NULL, 'DESAPARECIDA', NULL, '23232323', NULL, NULL, NULL, 0, 0, 0, '167', '60', 2, 1, 2016, 13, NULL, NULL, NULL, 1, 1, 3, 1, '2018-05-31 23:23:29', '2018-05-31 23:26:00', NULL);
INSERT INTO `desaparecidos_personas` (`id`, `apodo`, `edadAparente`, `edadExtravio`, `embarazo`, `tipoGestacion`, `numGestacion`, `rumoresBebe`, `pormenores`, `antecedentesJudiciales`, `organizacion`, `tipoPersona`, `otroDocIdentidad`, `numDocIdentidad`, `otroParentesco`, `correoElectronico`, `telefonos`, `tieneHijos`, `informante`, `notificaciones`, `estatura`, `peso`, `idPersona`, `idEdocivil`, `idOcupacion`, `idEscolaridad`, `idDialecto`, `idCargo`, `idParentesco`, `idDocumentoIdentidad`, `idCedula`, `idComplexion`, `idColorPiel`, `created_at`, `updated_at`, `deleted_at`) VALUES (12, 'DANI', '27', '24 a�os, 8 meses y 4 dias', 'NO', NULL, NULL, 'NO', NULL, NULL, NULL, 'DESAPARECIDA', NULL, '5445345646', NULL, NULL, NULL, 0, 0, 0, '181', '80', 4, 1, 2472, 12, NULL, NULL, NULL, 1, 2, NULL, NULL, '2018-05-31 23:33:55', '2018-05-31 23:33:55', NULL);
INSERT INTO `desaparecidos_personas` (`id`, `apodo`, `edadAparente`, `edadExtravio`, `embarazo`, `tipoGestacion`, `numGestacion`, `rumoresBebe`, `pormenores`, `antecedentesJudiciales`, `organizacion`, `tipoPersona`, `otroDocIdentidad`, `numDocIdentidad`, `otroParentesco`, `correoElectronico`, `telefonos`, `tieneHijos`, `informante`, `notificaciones`, `estatura`, `peso`, `idPersona`, `idEdocivil`, `idOcupacion`, `idEscolaridad`, `idDialecto`, `idCargo`, `idParentesco`, `idDocumentoIdentidad`, `idCedula`, `idComplexion`, `idColorPiel`, `created_at`, `updated_at`, `deleted_at`) VALUES (13, 'PEPE', '54', '50 a�os, 10 meses y 9 dias', 'NO', NULL, NULL, 'NO', NULL, NULL, NULL, 'DESAPARECIDA', NULL, '23232323', NULL, NULL, NULL, 0, 0, 0, '167', '60', 2, 1, 2016, 13, NULL, NULL, NULL, 1, 1, 3, 1, '2018-05-31 23:23:29', '2018-05-31 23:26:00', NULL);
INSERT INTO `desaparecidos_personas` (`id`, `apodo`, `edadAparente`, `edadExtravio`, `embarazo`, `tipoGestacion`, `numGestacion`, `rumoresBebe`, `pormenores`, `antecedentesJudiciales`, `organizacion`, `tipoPersona`, `otroDocIdentidad`, `numDocIdentidad`, `otroParentesco`, `correoElectronico`, `telefonos`, `tieneHijos`, `informante`, `notificaciones`, `estatura`, `peso`, `idPersona`, `idEdocivil`, `idOcupacion`, `idEscolaridad`, `idDialecto`, `idCargo`, `idParentesco`, `idDocumentoIdentidad`, `idCedula`, `idComplexion`, `idColorPiel`, `created_at`, `updated_at`, `deleted_at`) VALUES (14, 'DANI', '27', '24 a�os, 8 meses y 4 dias', 'NO', NULL, NULL, 'NO', NULL, NULL, NULL, 'DESAPARECIDA', NULL, '5445345646', NULL, NULL, NULL, 0, 0, 0, '181', '80', 4, 1, 2472, 12, NULL, NULL, NULL, 1, 2, NULL, NULL, '2018-05-31 23:33:55', '2018-05-31 23:33:55', NULL);
INSERT INTO `desaparecidos_personas` (`id`, `apodo`, `edadAparente`, `edadExtravio`, `embarazo`, `tipoGestacion`, `numGestacion`, `rumoresBebe`, `pormenores`, `antecedentesJudiciales`, `organizacion`, `tipoPersona`, `otroDocIdentidad`, `numDocIdentidad`, `otroParentesco`, `correoElectronico`, `telefonos`, `tieneHijos`, `informante`, `notificaciones`, `estatura`, `peso`, `idPersona`, `idEdocivil`, `idOcupacion`, `idEscolaridad`, `idDialecto`, `idCargo`, `idParentesco`, `idDocumentoIdentidad`, `idCedula`, `idComplexion`, `idColorPiel`, `created_at`, `updated_at`, `deleted_at`) VALUES (15, 'DANI', '27', '24 a�os, 8 meses y 4 dias', 'NO', NULL, NULL, 'NO', NULL, NULL, NULL, 'DESAPARECIDA', NULL, '5445345646', NULL, NULL, NULL, 0, 0, 0, '181', '80', 4, 1, 2472, 12, NULL, NULL, NULL, 1, 2, NULL, NULL, '2018-05-31 23:33:55', '2018-05-31 23:33:55', NULL);
INSERT INTO `desaparecidos_personas` (`id`, `apodo`, `edadAparente`, `edadExtravio`, `embarazo`, `tipoGestacion`, `numGestacion`, `rumoresBebe`, `pormenores`, `antecedentesJudiciales`, `organizacion`, `tipoPersona`, `otroDocIdentidad`, `numDocIdentidad`, `otroParentesco`, `correoElectronico`, `telefonos`, `tieneHijos`, `informante`, `notificaciones`, `estatura`, `peso`, `idPersona`, `idEdocivil`, `idOcupacion`, `idEscolaridad`, `idDialecto`, `idCargo`, `idParentesco`, `idDocumentoIdentidad`, `idCedula`, `idComplexion`, `idColorPiel`, `created_at`, `updated_at`, `deleted_at`) VALUES (16, 'PEPE', '54', '50 a�os, 10 meses y 9 dias', 'NO', NULL, NULL, 'NO', NULL, NULL, NULL, 'DESAPARECIDA', NULL, '23232323', NULL, NULL, NULL, 0, 0, 0, '167', '60', 2, 1, 2016, 13, NULL, NULL, NULL, 1, 1, 3, 1, '2018-05-31 23:23:29', '2018-05-31 23:26:00', NULL);
INSERT INTO `desaparecidos_personas` (`id`, `apodo`, `edadAparente`, `edadExtravio`, `embarazo`, `tipoGestacion`, `numGestacion`, `rumoresBebe`, `pormenores`, `antecedentesJudiciales`, `organizacion`, `tipoPersona`, `otroDocIdentidad`, `numDocIdentidad`, `otroParentesco`, `correoElectronico`, `telefonos`, `tieneHijos`, `informante`, `notificaciones`, `estatura`, `peso`, `idPersona`, `idEdocivil`, `idOcupacion`, `idEscolaridad`, `idDialecto`, `idCargo`, `idParentesco`, `idDocumentoIdentidad`, `idCedula`, `idComplexion`, `idColorPiel`, `created_at`, `updated_at`, `deleted_at`) VALUES (17, 'DANI', '27', '24 a�os, 8 meses y 4 dias', 'NO', NULL, NULL, 'NO', NULL, NULL, NULL, 'DESAPARECIDA', NULL, '5445345646', NULL, NULL, NULL, 0, 0, 0, '181', '80', 4, 1, 2472, 12, NULL, NULL, NULL, 1, 2, NULL, NULL, '2018-05-31 23:33:55', '2018-05-31 23:33:55', NULL);

-------------------------PERSONA--------------------

INSERT INTO `persona` ( `nombres`, `primerAp`, `segundoAp`, `fechaNacimiento`, `rfc`, `curp`, `sexo`, `esEmpresa`, `idEstadoOrigen`, `idNacionalidad`, `idMunicipioOrigen`) VALUES ( 'DANIEL', 'PALMEROS', 'ALARCON', '1900-01-01 00:00:00', 'AAAA000101', NULL, 'SIN INFORMACION', 0, NULL, 1, 2496);
INSERT INTO `persona` (`id`, `nombres`, `primerAp`, `segundoAp`, `fechaNacimiento`, `rfc`, `curp`, `sexo`, `esEmpresa`, `idEstadoOrigen`, `idNacionalidad`, `idMunicipioOrigen`, `created_at`, `updated_at`, `deleted_at`) VALUES (2, 'BERENICE', 'CONTRERAS', 'ALARCON', '1967-07-22 00:00:00', 'AAAA000101', 'COAB670722MDGNLR08', 'M', 0, 10, 1, 2496, '2018-05-31 23:23:29', '2018-05-31 23:23:29', NULL);
INSERT INTO `persona` (`id`, `nombres`, `primerAp`, `segundoAp`, `fechaNacimiento`, `rfc`, `curp`, `sexo`, `esEmpresa`, `idEstadoOrigen`, `idNacionalidad`, `idMunicipioOrigen`, `created_at`, `updated_at`, `deleted_at`) VALUES (3, 'JAVIER', 'PALMEROS', 'ALARCON', '1900-01-01 00:00:00', 'AAAA000101', NULL, 'SIN INFORMACION', 0, NULL, 1, 2496, '2018-05-31 23:32:44', '2018-05-31 23:32:44', NULL);
INSERT INTO `persona` (`id`, `nombres`, `primerAp`, `segundoAp`, `fechaNacimiento`, `rfc`, `curp`, `sexo`, `esEmpresa`, `idEstadoOrigen`, `idNacionalidad`, `idMunicipioOrigen`, `created_at`, `updated_at`, `deleted_at`) VALUES (4, 'DANIEL', 'ASSA', 'ALARCON', '1993-09-27 00:00:00', 'AAAA000101', 'AAAD930927HGTSLN02', 'H', 0, 11, 1, 2496, '2018-05-31 23:33:55', '2018-05-31 23:33:55', NULL);

-------------------------DESPARECIDOS DOMICILIOS--------------------


INSERT INTO `desaparecidos_domicilios` (`tipoDireccion`, `calle`, `numExterno`, `numInterno`, `telefono`, `idEstado`, `idMunicipio`, `idLocalidad`, `idColonia`, `idCodigoPostal`, `idDesaparecido`) VALUES ('LUGAR DE AVISTAMIENTO', 'JUÁREZ', '5', NULL, NULL, 30, 2105, 83377, 44818, 49172, 1);


-------------------------CEDULA PARTES CUERPO--------------------

INSERT INTO `cedula_partes_cuerpo` ( `tenia`, `observaciones`, `otraParticularidad`, `otraModificacion`, `otroTipoCuerpo`, `otroColor`, `posicion`, `idPartesCuerpo`, `idTamanoCuerpo`, `idTipoCuerpo`, `idColoresCuerpo`, `idPersonaDesaparecida` ) VALUES ( 'a', 'nada', NULL, NULL, NULL, NULL, NULL, 2, 7, 5, 5, 6, NULL, NULL);
INSERT INTO `cedula_partes_cuerpo` ( `tenia`, `observaciones`, `otraParticularidad`, `otraModificacion`, `otroTipoCuerpo`, `otroColor`, `posicion`, `idPartesCuerpo`, `idTamanoCuerpo`, `idTipoCuerpo`, `idColoresCuerpo`, `idPersonaDesaparecida` ) VALUES ( 'b', 'nada', NULL, NULL, NULL, NULL, NULL, 3, 7, 12, 3, 6, NULL, NULL);
INSERT INTO `cedula_partes_cuerpo` ( `tenia`, `observaciones`, `otraParticularidad`, `otraModificacion`, `otroTipoCuerpo`, `otroColor`, `posicion`, `idPartesCuerpo`, `idTamanoCuerpo`, `idTipoCuerpo`, `idColoresCuerpo`, `idPersonaDesaparecida` ) VALUES ( 'b', NULL, NULL, NULL, NULL, NULL, NULL, 4, 1, 12, 4, 6, NULL, NULL);
INSERT INTO `cedula_partes_cuerpo` ( `tenia`, `observaciones`, `otraParticularidad`, `otraModificacion`, `otroTipoCuerpo`, `otroColor`, `posicion`, `idPartesCuerpo`, `idTamanoCuerpo`, `idTipoCuerpo`, `idColoresCuerpo`, `idPersonaDesaparecida` ) VALUES ( 'b', NULL, NULL, NULL, NULL, NULL, NULL, 14, 7, 50, NULL, 6, NULL, NULL);
INSERT INTO `cedula_partes_cuerpo` ( `tenia`, `observaciones`, `otraParticularidad`, `otraModificacion`, `otroTipoCuerpo`, `otroColor`, `posicion`, `idPartesCuerpo`, `idTamanoCuerpo`, `idTipoCuerpo`, `idColoresCuerpo`, `idPersonaDesaparecida` ) VALUES ( 'b', NULL, NULL, NULL, NULL, NULL, NULL, 9, 11, NULL, 6, 6, NULL, NULL);
INSERT INTO `cedula_partes_cuerpo` ( `tenia`, `observaciones`, `otraParticularidad`, `otraModificacion`, `otroTipoCuerpo`, `otroColor`, `posicion`, `idPartesCuerpo`, `idTamanoCuerpo`, `idTipoCuerpo`, `idColoresCuerpo`, `idPersonaDesaparecida` ) VALUES ( 'a', 'nada', NULL, NULL, NULL, NULL, NULL, 2, 2, 5, 5, 8, NULL, NULL);
INSERT INTO `cedula_partes_cuerpo` ( `tenia`, `observaciones`, `otraParticularidad`, `otraModificacion`, `otroTipoCuerpo`, `otroColor`, `posicion`, `idPartesCuerpo`, `idTamanoCuerpo`, `idTipoCuerpo`, `idColoresCuerpo`, `idPersonaDesaparecida` ) VALUES ( 'b', 'nada', NULL, NULL, NULL, NULL, NULL, 3, 2, 11, 3, 8, NULL, NULL);
INSERT INTO `cedula_partes_cuerpo` ( `tenia`, `observaciones`, `otraParticularidad`, `otraModificacion`, `otroTipoCuerpo`, `otroColor`, `posicion`, `idPartesCuerpo`, `idTamanoCuerpo`, `idTipoCuerpo`, `idColoresCuerpo`, `idPersonaDesaparecida` ) VALUES ( 'b', NULL, NULL, NULL, NULL, NULL, NULL, 4, 5, 12, 4, 8, NULL, NULL);
INSERT INTO `cedula_partes_cuerpo` ( `tenia`, `observaciones`, `otraParticularidad`, `otraModificacion`, `otroTipoCuerpo`, `otroColor`, `posicion`, `idPartesCuerpo`, `idTamanoCuerpo`, `idTipoCuerpo`, `idColoresCuerpo`, `idPersonaDesaparecida` ) VALUES ( 'b', NULL, NULL, NULL, NULL, NULL, NULL, 14, 13, 50, NULL, 8, NULL, NULL);
INSERT INTO `cedula_partes_cuerpo` ( `tenia`, `observaciones`, `otraParticularidad`, `otraModificacion`, `otroTipoCuerpo`, `otroColor`, `posicion`, `idPartesCuerpo`, `idTamanoCuerpo`, `idTipoCuerpo`, `idColoresCuerpo`, `idPersonaDesaparecida` ) VALUES ( 'b', NULL, NULL, NULL, NULL, NULL, NULL, 9, 3, NULL, 6, 8, NULL, NULL);
INSERT INTO `cedula_partes_cuerpo` ( `tenia`, `observaciones`, `otraParticularidad`, `otraModificacion`, `otroTipoCuerpo`, `otroColor`, `posicion`, `idPartesCuerpo`, `idTamanoCuerpo`, `idTipoCuerpo`, `idColoresCuerpo`, `idPersonaDesaparecida` ) VALUES ( 'b',NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5, 7, 12, 2, 6, NULL, NULL);
INSERT INTO `cedula_partes_cuerpo` ( `tenia`, `observaciones`, `otraParticularidad`, `otraModificacion`, `otroTipoCuerpo`, `otroColor`, `posicion`, `idPartesCuerpo`, `idTamanoCuerpo`, `idTipoCuerpo`, `idColoresCuerpo`, `idPersonaDesaparecida` ) VALUES ( 'b',NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5, 13, 39, 3, 8, NULL, NULL);

------------------------- DESPARECIDOS CEDULA INVESTIGACION--------------------
INSERT INTO `desaparecidos_cedula_investigacion` (`entrevistadorNombres`, `entrevistadorPrimerAp`, `entrevistadorSegundoAp`, `entrevistadorCargo`, `carpeta`, `idCarpeta`, `interpreteNombres`, `interpretePrimerAp`, `interpreteSegundoAp`, `interpreteOrganizacion`, `otroDialecto`, `entrevistadorPrimeraVez`, `fechaVisita`, `desaparicionObservaciones`, `desaparicionRef`, `desaparicionFecha`, `nombresAvisto`, `primerApAvisto`, `segundoApAvisto`, `idParentescoAvisto`, `otroParentescoAvisto`, `vehiculoDescripcion`, `vehiculoPlacas`, `idDialecto`) VALUES ('FULANITO', 'SANCHEZ', 'MERENGANO', 'FISCAL 2DA ESP. EN LA INV. DE DELITOS DE VIOLENCIA CONTRA LA FAMILIA CONTRERAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'SI', '2018-05-31', 'REFIERE LA ENTREVISTADA QUE EL D�A 2 DE ENERO DEL 2017, PRUEBA', 'NINGUNA', '1998-11-23 22:00:00', 'JAVIER', 'ASSA', 'AGUILAR', 1, NULL, NULL, NULL, 1);
INSERT INTO `desaparecidos_cedula_investigacion` (`entrevistadorNombres`, `entrevistadorPrimerAp`, `entrevistadorSegundoAp`, `entrevistadorCargo`, `carpeta`, `idCarpeta`, `interpreteNombres`, `interpretePrimerAp`, `interpreteSegundoAp`, `interpreteOrganizacion`, `otroDialecto`, `entrevistadorPrimeraVez`, `fechaVisita`, `desaparicionObservaciones`, `desaparicionRef`, `desaparicionFecha`, `nombresAvisto`, `primerApAvisto`, `segundoApAvisto`, `idParentescoAvisto`, `otroParentescoAvisto`, `vehiculoDescripcion`, `vehiculoPlacas`, `idDialecto`) VALUES ('FULANITO', 'SANCHEZ', 'MERENGANO', 'FISCAL 2DA ESP. EN LA INV. DE DELITOS DE VIOLENCIA CONTRA LA FAMILIA CONTRERAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'SI', '2018-05-31', 'Refiere la entrevistada que el d�a 2 de enero del 2017, a las 9 de la noche aproximadamente su hija Briseida le dijo que saldr�a a lavar un poco de ropa al patio exterior de la casa, y pasado unos 20 o 30 minutos sali� a verla pero ya no la encontr�, busc�ndola por toda la colonia donde vive junto con su esposo, siendo avisados eso de las 11 de la noche por un sujeto de nombre Omar X que la menor se hab�a ido a M�xico con Luis Fernando vecino de la colonia.', 'NINGUNA 2', '2009-09-22 12:00:00', 'MARIA', 'ASSA', 'AGUILAR', 5, NULL, NULL, NULL, 1);

